services:
  mysql:
    image: mysql:8.0
    container_name: laravel_userstamps_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: laravel_userstamps_test
      MYSQL_USER: laravel_userstamps
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel_userstamps_network
    command: --default-authentication-plugin=mysql_native_password

  postgres:
    image: postgres:15
    container_name: laravel_userstamps_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: laravel_userstamps_test
      POSTGRES_USER: laravel_userstamps
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - laravel_userstamps_network

  # Optional: Add a Redis service for caching tests
  redis:
    image: redis:7-alpine
    container_name: laravel_userstamps_redis
    restart: unless-stopped
    networks:
      - laravel_userstamps_network

volumes:
  mysql_data:
  postgres_data:

networks:
  laravel_userstamps_network:
    driver: bridge 